apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-utensils-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-utensils-model
  template:
    metadata:
      labels:
        app: tf-serving-utensils-model
    spec:
      containers:
      - name: tf-serving-utensils-model
        image: kitchenware:xception_v4_10_0.956
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8500
